spring:
  application:
    name: USER-SERVICE
  profiles:
    active: dev
  config:
    import: configserver:http://cloud-config-server:9296
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10000
        max-interval: 2000
